config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  root 'pages#index'

  resources :products
  resource :cart, only: [:show, :destroy]
  resources :order_items, only: [:create, :update, :destroy]

  resources :comments, only: [:create]

  resources :users, only: [:show]

  resources :transactions, only: [:new, :create]

  get '/contact' => 'comments#index'

  get '/:id' => 'high_voltage/pages#show', as: :static

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end

  def destroy
    @cart = current_order.order_items
    @cart.destroy
    session[:order_id] = nil
    respond_to do |format|
      format.html { redirect_to products_path, notice: 'Your cart is empty!' }
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">
  <div class="row">
    <div class="col-xs-3">
    <%= image_tag product.photo.url, class: 'img-responsive img-thumbnail' %>
  </div>
    <div class="col-xs-5">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency(order_item.unit_price, precision: order_item.unit_price.round == order_item.unit_price ? 0 : 2) %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency(order_item.total_price, precision: order_item.total_price.round == order_item.total_price ? 0 : 2) %></span></h4>
      <% end %>
    </div>
  </div>
</div>



app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <h3 class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", products_path %> and add some items to your cart.
  </h3>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<% title "Cart" %><br><br><br>
<div class="container">
  <h1 class="text-center">Your Cart</h1><hr>
  <div class="shopping-cart">
    <%= render "shopping_cart" %>
  </div><hr>
  <div class="pull-right">
    <h3>Total: <%= number_to_currency(current_order.subtotal, precision: current_order.subtotal.round == current_order.subtotal ? 0 : 2) %></h3><hr>
    <% unless @order_items.size == 0 %>
      <%= link_to "Checkout", new_transaction_path, class: "btn btn-lg btn-warning" %>
      <%= link_to "Empty Cart", @cart, class: "btn btn-lg btn-warning", method: :delete, data: { confirm: 'Are you sure you want to clear your cart?' } %><br>
    <% end %>
  </div>
</div><br><br>