config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  root 'pages#index'

  resources :products
  resource :cart, only: [:show, :destroy]
  resources :order_items, only: [:create, :update, :destroy]

  resources :comments, only: [:create]

  resources :users, only: [:show]

  resources :transactions, only: [:new, :create]

  get '/contact' => 'comments#index'

  get '/:id' => 'high_voltage/pages#show', as: :static

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_cart!

  def new
    gon.client_token = generate_client_token
  end

  def create
    @result = Braintree::Transaction.sale(
              amount: current_order.subtotal,
              payment_method_nonce: params[:payment_method_nonce],
              customer: {
                first_name: params[:first_name],
                last_name: params[:last_name],
                email: current_user.email,
                phone: params[:phone]
              },
              shipping: {
                country_name: params[:country_name],
                street_address: params[:street_address],
                locality: params[:locality],
                region: params[:region]
              },
              options: {
                store_in_vault: true
              })

    if @result.success?
      @cart = current_order.order_items
      @cart.destroy
      session[:order_id] = nil
      redirect_to products_path, notice: "Your transaction has been successfully!"
    else
      flash[:alert] = "Something went wrong. Please try again!"
      gon.client_token = generate_client_token
      render :new
    end
  end

  private

    def generate_client_token
      Braintree::ClientToken.generate
    end

    def check_cart!
      if @order_items == 0
        redirect_to products_path, alert: "Please add some items to your cart before processing your transaction!"
      end
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_customer_form.html.erb
<p>Please enter your personal info:</p>
<%= text_field_tag :first_name, "", placeholder: "First Name", class: "span4 form-control" %><br>
<%= text_field_tag :last_name, "", placeholder: "Last Name", class: "span4 form-control" %><br>
<%= text_field_tag :phone, "", placeholder: "Phone", class: "span4 form-control" %><br>
<p>Shipping Address:</p>
<%= text_field_tag :country_name, "", placeholder: "Country", class: "span4 form-control" %><br>
<%= text_field_tag :region, "", placeholder: "Region", class: "span4 form-control" %><br>
<%= text_field_tag :locality, "", placeholder: "City", class: "span4 form-control" %><br>
<%= text_field_tag :street_address, "", placeholder: "Street Address", class: "span4 form-control" %><br>

app/views/transactions/new.html.erb
<% title "New Transaction" %><br><br><br><br><br><br><br><br><br><br>
<% unless @order_items == 0 %>
  <div class="container text-center">
    <div class="row">
      <div class="col-md-4 col-md-offset-4 well">
        <h1>New Transaction</h2>
        <%= form_tag transactions_path do %>
          <%= render 'customer_form' %>
          <p>Please enter your payment details:</p>
          <div id="dropin"></div>
          <%= submit_tag "Pay #{number_to_currency(current_order.subtotal, precision: current_order.subtotal.round == current_order.subtotal ? 0 : 2)}", class: "btn btn-default text-center" %>
          <% end %>
      </div>
    </div>
  </div>
<% else %>
  <%= controller.redirect_to products_path, alert: "Please add items to your cart before transaction!" %>
<% end %>

<script src="https://js.braintreegateway.com/v2/braintree.js"></script>