config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  root 'pages#index'

  resources :products
  resource :cart, only: [:show, :destroy]
  resources :order_items, only: [:create, :update, :destroy]

  resources :comments, only: [:create]

  resources :users, only: [:show]

  resources :transactions, only: [:new, :create]

  get '/contact' => 'comments#index'

  get '/:id' => 'high_voltage/pages#show', as: :static

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :text
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  private
    def set_order_status
      self.order_status_id = 1
    end

    def update_subtotal
      self[:subtotal] = subtotal
    end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
  belongs_to :user

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
    def product_present
      if product.nil?
        errors.add(:product, "is not valid or is not active.")
      end
    end

    def order_present
      if order.nil?
        errors.add(:order, "is not a valid order.")
      end
    end

    def finalize
      self[:unit_price] = unit_price
      self[:total_price] = quantity * self[:unit_price]
    end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items
  has_many :purchases
  has_many :buyers, through: :purchases

  validates :name, presence: true
  validates :price, presence: true
  validates :overview, presence: true, length: { minimum: 10, maximum: 250 }
  validates :description, presence: true

  has_attached_file :photo

  validates_attachment_presence :photo
  validates_attachment_content_type :photo, content_type: ['image/jpeg', 'image/png']
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  has_many :order_items, through: :purchases
  belongs_to :product
  belongs_to :buyer, class_name: 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :purchases, foreign_key: :buyer_id
  has_many :products, through: :purchases
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end

  def destroy
    @cart = current_order.order_items
    @cart.destroy
    session[:order_id] = nil
    respond_to do |format|
      format.html { redirect_to products_path, notice: 'Your cart is empty!' }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.order('created_at DESC').limit(10)
    @comment = Comment.new
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      flash[:success] = "Feedback was successfully created"
      redirect_to contact_path
    else
      redirect_to contact_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/pages_controller.rb
class PagesController < HighVoltage::PagesController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_admin!, except: [:index, :show]

  def index
    @products = Product.order('created_at DESC')
    @order_item = current_order.order_items.new
  end

  def show
    @order_item = current_order.order_items.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:success] = "Product was successfully created"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      flash[:success] = "Product was successfully updated"
      redirect_to product_path
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = "Product was successfully deleted"
      redirect_to products_path
    else
      render :show
    end
  end

  private

    def product_params
      params.require(:product).permit(:name, :overview, :price, :description, :photo)
    end

    def set_product
      @product = Product.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end

  def title(page_title)
    content_for :title, page_title.to_s
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger">
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_cart_text.html.erb
<div class="pull-right cart-btn">
  <%= link_to cart_path, class: 'btn btn-primary btn-md' do %>
    <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
    Cart: <span class="badge"><%= current_order.order_items.size %></span>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(image_tag("BMW_logo.png", alt: "BMW logo", width: 80, height: 80), root_path, id: "logo") %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav nav-tabs">
        <li class="<%= active_class(root_path) %>"><%= link_to "Home", root_path %></li>
        <li class="<%= 'active' if params[:controller] == 'products' %>"><%= link_to "Products", products_path %></li>
        <li class="<%= active_class(static_path(:about)) %>"><%= link_to "About", static_path(:about) %></li>
        <li class="<%= active_class(contact_path) %>"><%= link_to "Contact Us", contact_path %></li>

        <li class="nav-flash" style="<%= "display: none" unless flash %>">
          <div class="row">
            <div class="col-md-12 col-md-offset-2">
              <% flash.each do |message_type, message| %>
                <div class="alert alert-<%= message_type %>"><%= message %>
                </div>
              <% end %>
            </div>
          </div>
        </li>

        <div class="pull-right">
          <div class="nav_item">
            <% if signed_in?(:user) %>
              <%= link_to current_user.email, current_user %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default btn-default" %>
            <% elsif signed_in?(:admin) %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default btn-default pull-right" %>
            <% else %>
              <%= link_to "Log In",  new_user_session_path, class: "btn btn-default btn-default" %>
              <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default btn-default" %>
            <% end %>
          </div>
          <div class="cart-text">
            <%= render "layouts/cart_text" %>
          </div>
        </div>
      </ul>
    </div>
  </div>
</nav>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'BMW_logo.png' %>
</head>
<body>
  <%= render 'layouts/navigation' %>

  <%= yield %>


</body>
</html>

app/views/pages/about.html.erb
<% title "About" %>
<div class="container"><br><br>
  <h1>BMW</h1>
  <p>Bayerische Motoren Werke AG (English: Bavarian Motor Works), commonly known as BMW or BMW AG, is a German automobile, motorcycle and engine manufacturing company founded in 1916. BMW is headquartered in Munich, Bavaria, Germany. It also owns and produces Mini cars, and is the parent company of Rolls-Royce Motor Cars. BMW produces motorcycles under BMW Motorrad, and plug-in electric cars under the BMW i sub-brand. BMW is one of the best-selling luxury automakers in the world.</p>
  <h2>History</h2>
  <p>BMW was established as a business entity following a restructuring of the Rapp Motorenwerke aircraft manufacturing firm in 1917. After the end of World War I in 1918, BMW was forced to cease aircraft-engine production by the terms of the Versailles Armistice Treaty. The company consequently shifted to motorcycle production as the restrictions of the treaty started to be lifted in 1923, followed by automobiles in 1928–29.
  <br><br>
  The first car which BMW successfully produced and the car which launched BMW on the road to automobile production was the Dixi, it was based on the Austin 7 and licensed from the Austin Motor Company in Birmingham, England.
  <br><br>
  BMW's first significant aircraft engine (and commercial product of any sort) was the BMW IIIa inline-six liquid-cooled engine of 1918, much preferred for its high-altitude performance. With German rearmament in the 1930s, the company again began producing aircraft engines for the Luftwaffe. Among its successful World War II engine designs were the BMW 132 and BMW 801 air-cooled radial engines, and the pioneering BMW 003 axial-flow turbojet, which powered the tiny, 1944–1945–era jet-powered "emergency fighter", the Heinkel He 162 Spatz. The BMW 003 jet engine was first tested as a prime powerplant in the first prototype of the Messerschmitt Me 262, the Me 262 V1, but in 1942 tests the BMW prototype engines failed on takeoff with only the standby Junkers Jumo 210 nose-mounted piston engine powering it to a safe landing. The few Me 262 A-1b test examples built used the more developed version of the 003 jet, recording an official top speed of 800 km/h (497 mph). The first-ever four-jet aircraft ever flown, the sixth and eighth prototypes of the Arado Ar 234 jet reconnaissance-bomber, used BMW 003 jets for power. The improving reliability of the 003 as 1944 progressed, earmarked it as the required powerplant for airframe designs competing for the Jägernotprogramm's light fighter production contract, won by the Heinkel He 162 Spatz design. The BMW 003 aviation turbojet also found itself under consideration as the basic starting point for a pioneering turboshaft powerplant for German armored fighting vehicles in 1944–45, as the GT 101. Towards the end of the Third Reich BMW developed some military aircraft projects for the Luftwaffe, the BMW Strahlbomber, the BMW Schnellbomber and the BMW Strahljäger, but none of them were built.
  <br><br>
  By the year 1958, the automotive division of BMW was in financial difficulties and a shareholders meeting was held to decide whether to go into liquidation or find a way of carrying on. It was decided to carry on and to try to cash in on the current economy car boom enjoyed so successfully by some of Germany's ex-aircraft manufacturers such as Messerschmitt and Heinkel. The rights to manufacture the Italian Iso Isetta were bought; the tiny cars themselves were to be powered by a modified form of BMW's own motorcycle engine. This was moderately successful and helped the company get back on its feet. The controlling majority shareholder of the BMW Aktiengesellschaft since 1959 is the Quandt family, which owns about 46% of the stock. The rest is in public float.
  <br><br>
  BMW acquired the Hans Glas company based in Dingolfing, Germany, in 1966. Glas vehicles were briefly badged as BMW until the company was fully absorbed. It was reputed that the acquisition was mainly to gain access to Glas' development of the timing belt with an overhead camshaft in automotive applications, although some saw Glas' Dingolfing plant as another incentive. However, this factory was outmoded and BMW's biggest immediate gain was, according to themselves, a stock of highly qualified engineers and other personnel. The Glas factories continued to build a limited number of their existing models, while adding the manufacture of BMW front and rear axles until they could be closer incorporated into BMW.</p>
</div>

app/views/pages/contact.html.erb
<div class="jumbotron">
  <div class="container contact">
    <div class="pull-left">
      <h2><strong>BMW GROUP<br>HEADQUARTERS</strong></h2>
      <h3><strong>BMW AG</strong></h3>
      <p>
        Petuelring 130
        <br>
        80788 München
        <br>
        Germany
      </p>
    </div>
    <div class="pull-right contact-img">
      <%= image_tag("BMW-mini.jpg", alt: "Contact BMW HQ", width: '100%') %>
    </div>
  </div>
  <br>
  <div class="form-group text-center">
    <label for="feedback"><strong>Leave a Feedback:</strong></label>
    <textarea class="form-control center" rows="10" id="feedback"></textarea>
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</div>

app/views/pages/index.html.erb
<% title "Home" %>
<div class="jumbotron">
  <div class="container">
    <div class="thumbnail text-center">
      <%= image_tag("The-BMW-Welt-Experience_2.jpg", alt: "BMW office", class: 'about-img') %>
      <div class="caption">
        <h1>BMW Shop</h1>
        <p>This is our BMW Shop where you can buy a brand new BMW car!</p>
        <h2>Who we are?</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus eros, ultrices eget dictum sit amet, tempor sed libero. Cras mollis lobortis erat, vehicula rutrum mi egestas vitae. Nunc convallis quam tellus, rutrum vulputate quam sodales ut. Nullam sed sem lobortis, mattis neque sit amet, tempor massa. Nam gravida orci quis urna placerat volutpat. Sed varius nulla mauris, nec mollis nibh mattis et. Vestibulum porta hendrerit nisl, et malesuada libero efficitur tincidunt. Integer auctor non lacus at iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla facilisi. Quisque vehicula semper enim, in tincidunt leo condimentum ut. Nunc suscipit odio ante, nec dictum orci commodo a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel venenatis nunc. Praesent eu eros eget dui tincidunt fermentum. Nulla facilisi.</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_comments_form.html.erb
<div class="row">
  <%= form_for @comment do |f| %>
    <div class="form-group text-center">
      <%= f.label :feedback, "Leave a Feedback" %><br>
      <%= f.text_area :text, rows: 10, class: "form-control" %><br>

      <%= f.submit("Submit", class: "btn btn-primary btn-center") %>
    </div>
  <% end %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="col-md-5 alert alert-danger">
    <h5>Please correct the following errors:</h1>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>